CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(250) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR (200),
    USU_AREA_FORMACAO VARCHAR(500),
	USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MÉDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    USU_SENHA VARCHAR(250) NOT NULL,
    USU_NOME VARCHAR(250) NOT NULL, 
    PRIMARY KEY (USU_CODIGO)
);
CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    END_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(255) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE,
    PRIMARY KEY (ENQ_CODIGO)
);
CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE,
    PRIMARY KEY(URE_CODIGO)
    
);
CREATE TABLE IF NOT EXISTS PERGUNTA(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(250) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE,
    PRIMARY KEY(PER_CODIGO)
    
);
CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    FOREIGN KEY(FK_PER_CODIGO) REFERENCES PERGUNTA (PER_CODIGO) ON DELETE CASCADE,
    PRIMARY KEY (RES_CODIGO)
);
INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO ,  USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE,USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ("2025-12-10", "rubens.mosca", "saúde", "médico", "neorologia", "2000-06-05", "solteiro", "SP", "médio", "rubens@gmail.com", "12345", "RUBÃO");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO ,  USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE,USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ("2025-12-09", "neymar.santos", "engenheiro", "engenheiro civil", "civil", "2007-04-15", "solteiro", "MG", "fundamental", "neymar@gmail.com", "12345", "SANTOS");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO ,  USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE,USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ("2025-05-10", "thaiene.tessaro", "saúde", "médica", "indocrinologista", "2008-05-23", "casado", "SP", "superior", "thaiene@gmail.com", "12345", "TESSARO");

SELECT * FROM  USUARIO;

INSERT INTO ENQUETE (ENQ_DATA_FINAL, END_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME,FK_USU_CODIGO)
VALUES ("2025-10-10","2025-09-01","Obter a percepção do público sobre produtos, serviços ou propostas","ABOIL","1");

INSERT INTO ENQUETE (ENQ_DATA_FINAL, END_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME,FK_USU_CODIGO)
VALUES ("2025-11-30","2025-10-01","Descobrir o que o público gostaria de ver ou quais tópicos são relevantes","SHINDAI","2");

INSERT INTO ENQUETE (ENQ_DATA_FINAL, END_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME,FK_USU_CODIGO)
VALUES ("2025-05-20","2025-04-03","Criar interação e fortalecer o vínculo com o público em redes sociais","BANKAI","2");

SELECT * FROM ENQUETE;

