USE BD_SUPERMERCADO_FUNCIONARIO_PRODUTO_CONSUMIDOR;
	
INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("12345678000101", "Supermercado Grick", "(19) 98745-7788", "gricktambau@email.com", "Grick Street", "10000","TambaCity","SP");

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL,SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("98765432000145", "Supermercado Bom Preço", "(19) 93389-9238", "contato@bompreco.com", "Rua das Palmeiras", "250", "Campinas", "SP");

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL,SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("11223344000199", "Supermercado Central","(19) 99745-9768", "vendas@central.com", "Avenida Brasil", "850", "Ribeirão Preto", "SP");

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("55667788000122", "Supermercado Econômico","(19) 98625-9988", "contato@economico.com.br", "Rua XV de Novembro", "1300", "São José do Rio Preto", "SP");

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE,SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("33445566000155", "Supermercado Popular","(19) 98745-9990", "popular@mercado.com", "Avenida das Nações", "470", "Piracicaba", "SP");

INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME,PRO_PESO,PRO_QUANTIDADE,PRO_PRECO,PRO_DATA_VALIDADE)
VALUES ("7891234567890","Arroz 5kg", 5.0, 500, 26.90, '2025-12-25');

INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("7899876543210", "Feijão Carioca 1kg", 1.0, 300, 8.49, '2026-03-10');

INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("7894561237890", "Açúcar Refinado 1kg", 1.0, 400, 5.79, '2025-11-15');

INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("7897418529630", "Óleo de Soja 900ml", 0.9, 250, 7.29, '2026-06-05');

INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("7893692581470", "Macarrão Espaguete 500g", 0.5, 350, 4.59, '2026-01-20');

INSERT INTO CONSUMIDOR (CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES ("431.551.818-26", "Rubens Aparecido Moscardini Neto", "(19)99189-4660", "neto@gmail.com");

INSERT INTO CONSUMIDOR (CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES ("125.447.689-10", "Carla Mendes Rocha", "(11)98876-4321", "carla.rocha@gmail.com");

INSERT INTO CONSUMIDOR (CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES ("298.774.220-35", "João Pedro Ferreira", "(21)99754-1209", "joaopedro.ferreira@hotmail.com");

INSERT INTO CONSUMIDOR (CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES ("514.992.670-48", "Mariana Silva Costa", "(31)98560-7788", "mariana.costa@yahoo.com");

INSERT INTO CONSUMIDOR (CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES ("367.118.540-92", "Lucas Almeida Torres", "(41)99982-3355", "lucas.torres@gmail.com");

INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO,FK_SUP_CNPJ)
VALUES ("98765432100","José Vanderli", "1985-03-12", "11987654321", "ze_vanderlei@email.com", "carteira_ze_vanderlei.pdf", "1234", "56789", "2020-01-12", "44 horas","12345678000101");

INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES ("12378945601","Mariana Oliveira", "1990-07-25", "21999887766", "mariana.oliveira@email.com", "carteira_mariana.pdf", "2345", "11223", "2021-02-18", "40 horas","98765432000145");

INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES ("74185296300","Carlos Henrique Souza", "1988-11-09", "31998765432", "carlos.souza@email.com", "carteira_carlos.pdf", "5432", "33445", "2019-05-27", "44 horas","11223344000199");

INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES ("85236974100","Ana Paula Martins", "1995-09-14", "41999112233", "ana.martins@email.com", "carteira_ana.pdf", "6789", "55667", "2022-08-03", "36 horas","55667788000122");

INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES ("96325814700","Ricardo Lima", "1992-12-05", "11988776655", "ricardo.lima@email.com", "carteira_ricardo.pdf", "3456", "77889", "2023-03-10", "44 horas","33445566000155");

SELECT * FROM SUPERMERCADO;

/* CONSULTAR O AUMENTO DE R$2,00 NO PREÇO DOS PRODUTOS COM PREÇO ATUAL >= R$5,00*/

SELECT PRO_NOME AS "NOME",
PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
PRO_PRECO AS "PREÇO ATUAL",
TRUNCATE((PRO_PRECO + 2),2) AS "PREÇO COM AJUSTE DE R$ 2,00"
FROM PRODUTO
WHERE PRO_PRECO >=5;

/* CONSULTAR A REDUÇÃO DE R$1,00 NO PREÇO DOS PRODUTOS
COM PREÇO ATUAL ABAIXO DE R$5,00
/* 

SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
		PRO_PRECO AS "PREÇO ATUAL",
		TRUNCATE((PRO_PRECO-1),2) AS "PREÇO COM REDUÇÃO DE R$1,00"
FROM PRODUTO
WHERE PRO_PRECO <= 10;

/*
CONSULTAR COMO SERIA APLICAR UM DESCONTO DE 10% EM TODOS OS PRODUTOS
/*
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
		PRO_PRECO AS "PRECO ATUAL",
		(PRO_PRECO - (PRO_PRECO * 0.1)) AS "PREÇO COM DESCONTO DE 10%"
FROM PRODUTO;

/* AJUSTAR O ESTO DO PRIMEIRO PRODUTO, DIVIDINDO PELA METADE */
SELECT 	PRO_ID,
		PRO_NOME,
		PRO_CODIGO_BARRAS,
		PRO_QUANTIDADE
FROM PRODUTO;

UPDATE 	PRODUTO
SET		PRO_QUANTIDADE = PRO_QUANTIDADE/2
WHERE	PRO_ID = 1;

/*CONSULTAR TODOS OS PRODUTOS QUE TENHAM DATA DE VALIDADE ENTRE SETEMBRO DE 2025 E DEZEMBRO DE 2025*/
SELECT PRO_NOME AS "NOME",
       PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
       PRO_DATA_VALIDADE AS "DATA DE VALIDADE"
FROM   PRODUTO
WHERE  PRO_DATA_VALIDADE  BETWEEN '2025-09-01' AND '2025-12-31';

/* CONSULTAR TODOS OS PRODUTOS QUE TENHAM PREÇO MAIOR QUE R$10 OU MENOR QUE R$4*/
SELECT PRO_NOME AS "NOME",
	   PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
	   PRO_PRECO AS "PREÇO"
FROM   PRODUTO
WHERE PRO_PRECO >= 10 OR PRO_PRECO <= 4;
/* CONSULTAR OS DDS E TELEFONE DOS CONSUMIDORES SEPARADAMENTE */
SELECT CON_NOME AS "NOME DO CONSUMIDOR",
	   CON_CPF AS "CPF DO CONSUMIDOR",
       SUBSTRING(CON_TELEFONE, 2, 2) AS "DDD DO TELEFONE",
       SUBSTRING(CON_TELEFONE, 5, 10) AS "NÚMERO DO TELEFONE"
FROM  CONSUMIDOR;

/*GERAR UMA FRASE CONCATENANDO: RAZÃO SOCIAL, CNPJ, TELEFONE E EMAIL*/
SELECT CONCAT("RAZÃO SOCIAL:",
		CONCAT(SUP_RAZAO_SOCIAL,
			CONCAT("| CNPJ:",
				CONCAT(SUP_CNPJ,
					CONCAT("| TELEFONE:",
						CONCAT(SUP_TELEFONE,
							CONCAT(" | EMAIL:", SUP_EMAIL))))))) AS FRASE
FROM   SUPERMERCADO;

/*GERAR UMA CONSULTA QUE VERIFICA O STATUS DO ESTOQUE DOS PRODUTOS.
REGRAS:
1) QUANTIDADE <= 25: ESTOQUE BAIXO
2) QUANTIDADE > 25 E QUANTIDADE <= 100: ESTOQUE MÉDIO
3) QUANTIDADE > 100: ESTOQUE ALTO*/
SELECT PRO_NOME AS "NOME DO PRODUTO",
	   PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
       PRO_QUANTIDADE AS "QUANTIDADE",
       CASE
			WHEN PRO_QUANTIDADE <= 25 THEN "ESTOQUE BAIXO"
            WHEN PRO_QUANTIDADE > 25 AND PRO_QUANTIDADE < 100 THEN "ESTOQUE MÉDIO"
            WHEN PRO_QUANTIDADE >= 100 THEN "ESTOQUE ALTO"
		END AS " NÍVEL DE ESTOQUE"
FROM  PRODUTO;

/*GERAR UMA CONSULTA QUE VERIFICA O PESO DOS PRODUTOS.
RETORNAR: NOME, CODIGO DE BARRAS, QUANTIDADE, PESO E DATA DE VALIDADE
REGRAS:
1) QUANTIDADE <= 5: PESO BAIXO
2) QUANTIDADE > 5 E QUANTIDADE <= 50: PESO MÉDIO
3) QUANTIDADE > 50: PESO ALTO*/
SELECT	PRO_NOME AS "NOME DO PRODUTO",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_QUANTIDADE AS "QUANTIDADE",
        PRO_PESO AS "PESO",
        PRO_DATA_VALIDADE AS "DATA DE VALIDADE",
        CASE
			WHEN PRO_PESO <=5 THEN "PESO BAIXO"
            WHEN PRO_PESO > 5 AND PRO_PESO <= 50 THEN "PESO MÉDIO"
            WHEN PRO_PESO > 50 THEN "PESO ALTO"
		END AS "CLASSIFICAÇÃO DO PESO"
FROM  PRODUTO;

/*CONTAR QUANTOS CONSUMIDORES TEMOS CADASTRADOS*/
SELECT COUNT(*)
FROM CONSUMIDOR;

SELECT COUNT(*)
FROM FUNCIONARIO;

SELECT COUNT(*)
FROM SUPERMERCADO;

/* SOMAR O PREÇO TOTAL DE TODOS OS PRODUTOS CADASTRADOS*/
SELECT	SUM(PRO_PRECO)
FROM	PRODUTO;

SELECT	CONCAT("R$ ", TRUNCATE(SUM(PRO_PRECO),2)) AS "SOMA TOTAL"
FROM PRODUTO;

/*CALCULAR A MÉDIA DE PREÇOS DOS PRODUTOS*/
SELECT AVG(PRO_PRECO)
FROM PRODUTO;

SELECT CONCAT("R$ ", TRUNCATE(AVG(PRO_PRECO),2)) AS "MÉDIA DE PREÇO"
FROM PRODUTO;

/* SELECIONAR O PRODUTO MAIS CARO*/
SELECT MAX(PRO_PRECO)
FROM PRODUTO;

/*SELECIONAR O ESTOQUE COM MAIOR QUANTIDADE*/
SELECT MAX(PRO_QUANTIDADE)
FROM PRODUTO;

SELECT MIN(PRO_QUANTIDADE)
FROM PRODUTO;

SELECT MIN(PRO_PRECO)
FROM PRODUTO;

SELECT NOW() FROM DUAL;

SELECT	FUN_NOME AS " NOME DO FUNCIONÁRIO",
		DATE_FORMAT(FUN_DATA_NASCIMENTO, "%d/%m/%Y") AS "DATA DE NASCIMENTO",
        TIMESTAMPDIFF (YEAR,FUN_DATA_NASCIMENTO, NOW()) AS "IDADE"
FROM FUNCIONARIO;

/* FUNÇÕES MATEMÁTICAS:
ABS - VALOR ABSOLUTO DE UM NÚMERO
ROUND-ARREDONDAR
POWER-POTÊNCIA*/
SELECT ABS(-10),
	   ROUND(PRO_PRECO) AS "PREÇO ARREDONDADO",
       POWER(PRO_PRECO, 2) AS "PREÇO ELEVADOS AO QUADRADO"
FROM PRODUTO;

/*UPPER, LOWER, TRIM*/
SELECT UPPER(FUN_NOME) AS "MAIÚSCULAS",
	   LOWER(FUN_NOME) AS "MINÚSCULAS",
       TRIM("     RUBENS") AS "TIRANDO ESPAÇOS"
FROM FUNCIONARIO;

SELECT	PRO_QUANTIDADE,
		COUNT(*) AS "REPETIÇÕES"
FROM 	PRODUTO
GROUP BY PRO_QUANTIDADE;

/*union*/
SELECT	FUN_NOME,
		FUN_CPF
FROM    FUNCIONARIO
UNION
SELECT	FUN_NOME,
		FUN_CPF
FROM	FUNCIONARIO;

SELECT * FROM PRODUTO;

/*UNION*/
SELECT	PRO_NOME
FROM	PRODUTO
UNION
SELECT 	"Arroz 5kg"
FROM 	DUAL
UNION	
SELECT	"Iogurt do Bob Esponja"
FROM	DUAL;

/*UNION*/
SELECT	PRO_NOME
FROM	PRODUTO
UNION
SELECT 	"Arroz 5kg"
FROM 	DUAL
UNION	ALL
SELECT	"Iogurt do Bob Esponja"
FROM	DUAL;

/*SELECT COM WHERE*/
SELECT	FUN_NOME		AS "NOME DO FUNCIONÁRIO",
		FUN_CPF			AS "CPF DO FUNCIONÁRIO",
        FUN_DATA_NASCIMENTO		AS "DATA DE NASCIMENTO",
		TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) AS "IDADE"
FROM 	FUNCIONARIO
WHERE	TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) >=25
AND	TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) <=35;

/*RETORNAR OS FUNCIONÁRIOS, CONSUMIDORES E SUPERMERCADOS COM EMAIL IGUAL A HOTMAIL OU OUTLOOK*/
SELECT	CON_NOME AS "NOME",
		CON_CPF AS "CPF/CNPJ",
        CON_TELEFONE AS "TELEFONE",
        CON_EMAIL AS "EMAIL",
        "CONSUMIDOR" AS "TIPO"
FROM 	CONSUMIDOR
WHERE 	UPPER(CON_EMAIL) LIKE "%EMAIL%"
OR UPPER(CON_EMAIL) LIKE "%OUTLOOK%"
UNION
SELECT	FUN_NOME AS "NOME",
		FUN_CPF AS "CPF/CNPJ",
        FUN_TELEFONE AS "TELEFONE",
        FUN_EMAIL AS "EMAIL",
        "FUNCIONARIO" AS "TIPO"
FROM FUNCIONARIO
WHERE UPPER(FUN_EMAIL) LIKE "%EMAIL%"
OR	UPPER(FUN_EMAIL) LIKE "%OUTLOOK%"
UNION
SELECT 	SUP_RAZAO_SOCIAL AS "NOME",
		SUP_CNPJ AS "CPF/CNPJ",
        SUP_TELEFONE AS "TELEFONE",
        SUP_EMAIL AS "EMAIL",
        "SUPERMERCADO" AS "TIPO"
FROM SUPERMERCADO
WHERE UPPER(SUP_EMAIL) LIKE "%EMAIL%"
OR	UPPER(SUP_EMAIL) LIKE "%OUTLOOK%";

/*cross JOIN: RETORNAR TODOS OS PRODUTOS E OS SUPERMERCADOS EM QUE SÃO VENDIDOS*/
SELECT	PRODUTO.PRO_NOME AS "NOME",
		PRODUTO.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        SUPERMERCADO.SUP_RAZAO_SOCIAL AS "RAZÃO SOCIAL"
FROM 	SUPERMERCADO_PRODUTO
CROSS JOIN	SUPERMERCADO
CROSS JOIN 	PRODUTO
WHERE 		PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID
AND 		SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ;

/*INNER JOIN: RETORNA APENAS PRODUTOS QUE FORAM COMPRADOS POR ALGUM CONSUMIDOR*/
SELECT	PRODUTO_CONSUMIDOR.PCO_ID AS "ID DA COMPRA",
		PRODUTO.PRO_NOME AS "NOME DO PRODUTO",
        PRODUTO.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        CONSUMIDOR.CON_NOME AS "NOME DO CONSUMIDOR",
        CONSUMIDOR.CON_CPF AS "CPF CONSUMIDOR"
FROM	PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF);

/*EXERCÍCIO COM INNER JOIN*/
SELECT	SUPERMERCADO.SUP_RAZAO_SOCIAL AS "RAZÃO SOCIAL",
		FUNCIONARIO.FUN_NOME AS "NOME DO FUNCIONÁRIO"
FROM	SUPERMERCADO
INNER JOIN FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/*EXERCÍCIO 2 COM INNER JOIN
RETORNAR APENAS OS PRODUTOS QUE EXISTAM EM UM SUPERMERCADO
RETORNAR O NOME DO PRODUTO E O NOME DO SUPERMERCADO QUE ELE ESTÁ DISPONÍVEL*/
SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	SUPERMERCADO_PRODUTO
INNER JOIN PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*LEFT JOIN*/
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS,PRO_NOME,PRO_PESO,PRO_QUANTIDADE,PRO_PRECO,PRO_DATA_VALIDADE)
VALUES				("3333333", "KITKAT", "30", "1500", 4.50,"2026-01-01");

SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	PRODUTO
LEFT JOIN SUPERMERCADO_PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
LEFT JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

SELECT * FROM SUPERMERCADO;

SELECT PRODUTO.PRO_NOME,
	   SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM   PRODUTO
RIGHT JOIN SUPERMERCADO_PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
RIGHT JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*SELECT COM LEFT JOIN E RIGHT JOIN*/
SELECT *
FROM (
		SELECT S.SUP_RAZAO_SOCIAL AS RAZAO_SOCIAL,
			   F.FUN_NOME AS NOME_FUNCIONARIO,
               P.PRO_NOME AS NOME_PRODUTO,
               C.CON_NOME AS NOME_CONSUMIDOR
		FROM   SUPERMERCADO S
        LEFT JOIN FUNCIONARIO F ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
        LEFT JOIN SUPERMERCADO_PRODUTO SP ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
        LEFT JOIN PRODUTO P ON (SP.FK_PRO_ID = P.PRO_ID)
        LEFT JOIN PRODUTO_CONSUMIDOR PC ON (P.PRO_ID = PC.FK_PRO_ID)
        LEFT JOIN CONSUMIDOR C ON (PC.FK_CON_CPF = C.CON_CPF)
        UNION
        SELECT S.SUP_RAZAO_SOCIAL AS RAZAO_SOCIAL,
			   F.FUN_NOME AS NOME_FUNCIONARIO,
               P.PRO_NOME AS NOME_PRODUTO,
               C.CON_NOME AS NOME_CONSUMIDOR
		FROM   SUPERMERCADO S
        RIGHT JOIN FUNCIONARIO F ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
        RIGHT JOIN SUPERMERCADO_PRODUTO SP ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
        RIGHT JOIN PRODUTO P ON (SP.FK_PRO_ID = P.PRO_ID)
        RIGHT JOIN PRODUTO_CONSUMIDOR PC ON (P.PRO_ID = PC.FK_PRO_ID)
        RIGHT JOIN CONSUMIDOR C ON (PC.FK_CON_CPF = C.CON_CPF)
) SELECT_EXTERNO
ORDER BY	SELECT_EXTERNO.RAZAO_SOCIAL ASC,
			SELECT_EXTERNO.NOME_FUNCIONARIO DESC,
            SELECT_EXTERNO.NOME_PRODUTO		ASC,
            SELECT_EXTERNO.NOME_CONSUMIDOR  DESC;

/*EXERCICIO 1*/
SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	SUPERMERCADO_PRODUTO
INNER JOIN PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*EXERCICIO 2*/
SELECT FUNCIONARIO.FUN_NOME,
	   SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM   SUPERMERCADO
INNER JOIN FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/*EXERCICIO 3*/
SELECT CONSUMIDOR.CON_NOME,
	   PRODUTO.PRO_NOME
FROM   PRODUTO_CONSUMIDOR
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.CON_CPF = CONSUMIDOR.FK_CON_CPF)
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.PRO_ID = PRODUTO.FK_PRO_ID);

/*EXERCICIO 4 */
SELECT PRODUTO.PRO_NOME,
	   CONSUMIDOR.CON_NOME
FROM PRODUTO_CONSUMIDOR
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF)
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO_PRO_ID);


/*exercício left join */
SELECT	SUPERMERCADO.SUP_RAZAO_SOCIAL,
		PRODUTO.PRO_NOME
FROM	SUPERMERCADO
LEFT JOIN SUPERMERCADO_PRODUTO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
LEFT JOIN PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);


/* exercício 2 */
SELECT	FUNCIONARIO.FUN_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	FUNCIONARIO
LEFT JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);


/* exercício 3 */
SELECT	CONSUMIDOR.CON_NOME,
		PRODUTO.PRO_NOME
FROM	CONSUMIDOR
LEFT JOIN PRODUTO_CONSUMIDOR ON (CONSUMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF)
LEFT JOIN PRODUTO ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID);


/* exercício 4 */
SELECT	PRODUTO.PRO_ID,
		CONSUMIDOR.CON_NOME
FROM	PRODUTO
LEFT JOIN PRODUTO_CONSUMIDOR ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID)
LEFT JOIN PRODUTO ON (CONSUMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF);


/*exercício 5 */
SELECT	SUPERMERCADO.SUP_RAZAO_SOCIAL,
		FUNCIONARIO.FUN_NOME
FROM	SUPERMERCADO
LEFT JOIN FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);


/*exercício com right join */
SELECT 	SUPERMERCADO.SUP_RAZAO_SOCIAL,
		PRODUTO.PRO_NOME
FROM 	SUPERMERCADO
RIGHT JOIN 	SUPERMERCADO_PRODUTO ON (SUPERMERCADO.FK_SUP_CNPJ = SUPERMERCADO.SUP_CNPJ)
RIGHT JOIN	PRODUTO ON (SUPERMERCADO.FK_PRO_ID = PRODUTO.PRO_ID);


/*exercício 2*/
SELECT	CONSUMIDORES.CON_NOME,
		PRODUTO.PRO_NOME
FROM	CONSUMIDOR
RIGHT JOIN	PRODUTO_CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF)
RIGHT JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID);


/*exercício 3*/
SELECT	FUNCIONARIO.FUN_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	FUNCIONARIO
RIGHT JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);


/*exercício 4*/
SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL,
	   PRODUTO.PRO_NOME
FROM   SUPERMERCADO
RIGHT JOIN SUPERMERCADO_PRODUTO ON (SUPERMERCADO.FK_SUP_CNPJ = SUPERMERCADO.SUP_CNPJ)
RIGHT JOIN PRODUTO ON (SUPERMERCADO.FK_PRO_ID = PRODUTO.PRO_ID);


/*exercício 5*/
SELECT	CONSUMIDORES.CON_NOME,
		PRODUTO.PRO_NOME
FROM	CONSUMIDOR
RIGHT JOIN	PRODUTO_CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF)
RIGHT JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID);

/*SELECIONAR apenas os produtos que possuem registro em um supermercado e que foram comprados por um consumidor*/
SELECT P.PRO_NOME AS "NOME DO PRODUTO",
	   P.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
       P.PRO_PRECO AS "PREÇO DE PRODUTO"
FROM   PRODUTO P
WHERE P.PRO_ID IN (SELECT SP.FK_PRO_ID FROM SUPERMERCADO_PRODUTO SP)
AND   P.PRO_ID IN (SELECT PC.FK_PRO_ID FROM PRODUTO_CONSUMIDOR PC);
		
/**/