CREATE DATABASE IF NOT EXISTS APLICATIVO_MUSICA;
USE APLICATIVO_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO VARCHAR(300)
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    FOTO BLOB,
    QTD_MUSICAS INTEGER NOT NULL,
    FK_ARTISTA_CPF VARCHAR(14),
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    LETRA VARCHAR(1000) NOT NULL,
    CAPA BLOB,
    FK_GENERO_ID INTEGER,
    FK_ALBUM_ID INTEGER,
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID) ON DELETE CASCADE
);


