CREATE DATABASE IF NOT EXISTS BD_PASSAGENS_AEREAS;
USE BD_PASSAGENS_AEREAS;

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATAA DATE,
    VALOR INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(14) PRIMARY KEY,
    IDADE VARCHAR(2) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    PASSAPORTE VARCHAR(30) NOT NULL,
    VOTO BLOB
);	

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(200) NOT NULL,
    VALOR DOUBLE NOT NULL,
    FK_VOO_ID INTEGER NOT NULL,
    FK_PASSAGEIRO_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_VOO_ID) REFERENCES VOO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PASSAGEIRO_CPF) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE
);