CREATE DATABASE IF NOT EXISTS BD_STEAM_VIDEO;
USE BD_STEAM_VIDEO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IDADE INTEGER NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    TEMPO INTEGER NOT NULL,
    FK_CATEGORIA_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CATEGORIA_ID) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VISUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    INTERACAO INTEGER NOT NULL,
    FK_VIDEO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_VIDEO_ID) REFERENCES VIDEO(ID) ON DELETE CASCADE
);