CREATE DATABASE IF NOT EXISTS BD_GEREN_BIBLIO_DIG;
USE BD_GEREN_BIBLIO_DIG;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE INTEGER,
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(1200),
    FOTO BLOB,
    EDITORA VARCHAR(255),
    FK_CPF_AUTOR VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_CPF_AUTOR) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LIVRO_LEITOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_LIVRO_DIGITAL INTEGER NOT NULL,
    FK_CPF_LEITOR VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_LEITOR) REFERENCES LEITOR(CPF) ON DELETE CASCADE
);