CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE;
USE BD_GESTAO_ESTOQUE;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(850) NOT NULL,
    QUANTIDADE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALIDADE DATE,
    QUANTIDADE INTEGER NOT NULL,
    PRECO DOUBLE NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FOTO BLOB,
    FK_ID_CATEGORIA INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FORNECIMENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PRODUTO INTEGER NOT NULL,
    FK_CNPJ_FORNECEDOR VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE
);