CREATE DATABASE IF NOT EXISTS BD_GERENCIAMENTO_PROJETOS;
USE BD_GERENCIAMENTO_PROJETOS;

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(200) NOT NULL,
    NOME VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(200) NOT NULL,
    FK_PROJETO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_PROJETO_ID) REFERENCES PROJETO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS REALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_TAREFA_ID INTEGER NOT NULL,
    FK_FUNCIONARIO_CPF VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_TAREFA_ID) REFERENCES TAREFA(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_FUNCIONARIO_CPF) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);