CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS;
USE BD_ALUGUEL_PRODUTOS;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR (14) NOT NULL,
    NOME VARCHAR (150) NOT NULL,
    TELEFONE VARCHAR (15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL, 
	DESCRICAO VARCHAR (500) NOT NULL,
	PRECO DECIMAL NOT NULL,
	QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE,
    DATA_DEVOLUCAO DATE,
    VALOR_TOTAL DECIMAL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
    );
    
-- DML - LINGUAGEM DE MANIPULAÇÃO
-- INSERT - INSERIR
INSERT INTO CLIENTE (EMAIL,TELEFONE,NOME,CPF)
VALUES ("email@email.com","199999999","123456789","Leo");

INSERT INTO CLIENTE (EMAIL, TELEFONE,NOME,CPF)
VALUES ("netomoscardini10@gmail.com","19991894660","rubens","43155181826");

INSERT INTO CLIENTE (NOME,EMAIL,TELEFONE, CPF)
VALUES ("rubens","netomoscardini10@gmail.com","19991894660","1212121212");

-- SELECT - SELECIONAR
SELECT * FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = "asasas@gmail.com"
WHERE CLIENTE_ID = 1;

UPDATE CLIENTE
SET EMAIL = "wwnwmmdmomsamdo@gmail.com"
WHERE CLIENTE_ID = 2;

-- INSERT PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("MacBook M4","Notebook Apple",4789.90,5);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Galaxy S24", "Smartphone Samsung", 3500.00, 10);

INSERT INTO PRODUTO (NOME, DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Monitor LG 27'", "Monitor 4K UHD", 1800.00, 7);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Headset HyperX", "Fone Gamer com microfone", 450.00, 15);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Mouse Logitech MX", "Mouse sem fio", 380.00, 20);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Notebook Dell", "Inspiron 15, 8GB RAM, SSD 256GB", 3200.00, 8);

INSERT INTO PRODUTO (NOME, DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Cadeira Gamer", "Preta com ajuste ergonômico", 950.00, 5);

INSERT INTO PRODUTO (NOME,DESCRICAO, PRECO,QTD_DISPONIVEL)
VALUES ("Smart TV LG 55'", "4K UHD, WebOS", 2800.00, 6);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Notebook Acer Aspire 5", "Intel i5, 8GB RAM, SSD 512GB", 3200.00, 12);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES("PC Gamer Ryzen 5", "RTX 3060, 16GB RAM, SSD 1TB", 6200.00, 5);	

SELECT * FROM PRODUTO;
-- ATUALIZAR UM REGISTRO (UPDATE)
UPDATE PRODUTO
SET 	PRECO = 3500
WHERE PRODUTO_ID = 1;

UPDATE PRODUTO
SET	PRECO = 2500
WHERE PRODUTO_ID =3;

UPDATE PRODUTO
SET PRECO = 3798
WHERE PRODUTO_ID = 4;

UPDATE PRODUTO
SET PRECO = 4000
WHERE PRODUTO_ID = 5;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 7
WHERE PRODUTO_ID = 6;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 2
WHERE PRODUTO_ID = 8;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 1
WHERE PRODUTO_ID = 9;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 3
WHERE PRODUTO_ID = 7;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 6
WHERE PRODUTO_ID = 5;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 7
WHERE PRODUTO_ID = 4;

-- INSERER ALUGUEL
SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;

INSERT INTO ALUGUEL (	DATA_ALUGUEL,
						DATA_DEVOLUCAO,
                        VALOR_TOTAL,
                        FK_CLIENTE_ID,
                        FK_PRODUTO_ID)
VALUES					(	"2025-09-24",
							"2025-10-01",
                            7890,
                            3,
                            2);
                            
INSERT INTO ALUGUEL( DATA_ALUGUEL,
					DATA_DEVOLUCAO,
                    VALOR_TOTAL,
					FK_CLIENTE_ID,
                    FK_PRODUTO_ID)
VALUES 				( 	"2025-09-24",
						"2025-09-25",
                        1200,
                        1,
                        4);
                        
INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-08-15", "2025-08-20", 560, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-08-30", "2025-08-29", 897, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-08-16", "2025-08-22", 122, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-08-4", "2025-08-1", 579.00, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-07-22", "2025-08-13",789.00,2,1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-08-15", "2025-09-31", 9899.00, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-08-11", "2025-09-21", 1400.00, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-08-9", "2025-09-12", 389.00, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-08-9", "2025-10-9", 450.00, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-10-15", "2025-11-28", 1111.00, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-10-2", "2025-11-31", 3212.00, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2026-07-1", "2026-08-20", 3455.00, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2026-07-12", "2026-08-16", 560, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2025-08-10", "2025-08-21", 5400.00, 2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2027-10-10", "2027-12-12", 789.00,2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2027-11-14", "2027-12-24", 490.00,2, 1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ( "2028-04-23", "2028-05-13", 5732.00,2,1); 


							
                            
SELECT * FROM ALUGUEL;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2040-10-10"
WHERE ALUGUEL_ID = 2;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2033-12-08"
WHERE ALUGUEL_ID = 3;

UPDATE ALUGUEL 
SET DATA_DEVOLUCAO = "2022-09-11"
WHERE ALUGUEL_ID = 4;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2023-07-31"
WHERE ALUGUEL_ID = 5;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2021-03-22"
WHERE ALUGUEL_ID = 6;

UPDATE ALUGUEL 
SET DATA_DEVOLUCAO = "2030-09-10"
WHERE ALUGUEL_ID = 7;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2027-10-10"
WHERE ALUGUEL_ID = 8;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2027-12-02"
WHERE ALUGUEL_ID = 9;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO = "2029-02-17"
WHERE ALUGUEL_ID = 1;

-- APAGAR UM REGISTRO (DELETE)
DELETE FROM CLIENTE WHERE CLIENTE_ID = 1;

DELETE FROM PRODUTO
WHERE PRODUTO_ID= 4;

DELETE FROM ALUGUEL
WHERE ALUGUEL_ID = 3;

SELECT * FROM CLIENTE;

SELECT *
FROM CLIENTE
WHERE CLIENTE_ID = 2;

SELECT NOME,
		PRECO
FROM 	PRODUTO
WHERE 	PRODUTO_ID =3;


							